# -*- coding: utf-8 -*-
"""fashion550k_for_fastai.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h9mOj6TzHomqWBV0jSq_jwKpwFxXsTHB
"""

import numpy as np
import os

noisy_ann_path = "annotation/noisy.npy"
verified_ann_path = "annotation/verified.npy"
photo_basedir = "photos"
photo_files_path = "photos.txt"

def create_fastai_labels_csv(ann_path, csv_path=None,
                             photo_txt_path=photo_files_path, photo_basedir=photo_basedir):
    with open(photo_txt_path, "r") as f:
        photos = [os.path.join(photo_basedir, l.strip()) for l in f]
    if not csv_path:
        csv_path = os.path.basename(ann_path) + ".csv"
    data = np.load(ann_path)
    num_ids = data.shape[0]
    labels = [[] for _ in range(num_ids)]
    for row, label in zip(*np.where(data == 1)):
        labels[row].append(label)
    with open(csv_path, "w") as f:
        f.writelines(("{},{}\n".format(photos[i], " ".join([str(v) for v in vals])) for i, vals in enumerate(labels)))

create_fastai_labels_csv(noisy_ann_path)
create_fastai_labels_csv(verified_ann_path)
